# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-20 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapp',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b'documents/'),
            preserve_default=False,
        ),
    ]
