# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_interests'),
        ('rentapp', '0002_rentapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapp',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
